services:
  nginx-waf:
    image: 1posix/waf-nginx:latest
    container_name: nginx-waf
    restart: unless-stopped
    hostname: waf-nginx
    ports:
      - "80:80"
    # - "32400:32400" If you want another port listening you had to place it here and adjust Nginx config
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/modsec/modsecurity.conf:/etc/nginx/modsec/modsecurity.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./config/owasp-crs/rules:/etc/nginx/owasp-crs/rules
      - ./config/owasp-crs/crs-setup.conf:/etc/nginx/owasp-crs/crs-setup.conf
      - ./config/custom/html:/usr/share/nginx/html/custom:ro
      - ./config/custom/snippets/error-pages.conf:/etc/nginx/snippets/error-pages.conf:ro
      - ./logs:/var/log/nginx
    networks:
      - proxy-network
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - TZ=Europe/Paris
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy-network:
    driver: bridge
    name: waf-network
